{{- if or .Values.sftTokenSecret .Values.multiSFT.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sftd.fullname" . }}-secret
  labels:
    {{- include "sftd.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.multiSFT.enabled .Values.sftTokenSecret }}
  {{- fail "multiSFT.enabled is true and .Values.sftTokenSecret is also set; please set the secret at multiSFT.secret" }}
  {{- end }}
  {{- if and .Values.multiSFT.enabled (not .Values.multiSFT.discoveryRequired) }}
  zrest_secret.txt: {{ required "must specify authentication secret" .Values.multiSFT.secret | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.multiSFT.enabled) .Values.sftTokenSecret }}
  sftTokenSecret.txt: {{ .Values.sftTokenSecret | b64enc | quote }}
  {{- end }}
{{- end }}
