name: Validate Helm charts
on:
  push:
    paths:
      - "charts/**"
      - ".github/workflows/helm_validate.yml"
    branches: ["master", "release-**"]
jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
      - name: Setup Kubeconform
        uses: bmuschko/setup-kubeconform@5ccaecbbf012bcb1eeeab66e649db64a477ade8f # v1.0.0
      - name: Render and test Helm chart
        run: >
          helm template sftd charts/sftd --values ${TEST_VALUES} | kubeconform -summary -verbose -schema-location default -schema-location ${CRD_SCHEMA_LOCATION}
        env:
          TEST_VALUES: charts/sftd/values.test.yaml
          CRD_SCHEMA_LOCATION: "https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json"
